### ISSUE TITLE
Trying to install on Mac - TypeError

### ISSUE THREAD

**Issue by handloomweaver** [strohel/Ceygen#2]
running test
running build
running build_py
creating build
creating build/lib.macosx-10.8-x86_64-2.7
creating build/lib.macosx-10.8-x86_64-2.7/ceygen
copying ceygen/**init**.py -> build/lib.macosx-10.8-x86_64-2.7/ceygen
creating build/lib.macosx-10.8-x86_64-2.7/ceygen/tests
copying ceygen/tests/**init**.py -> build/lib.macosx-10.8-x86_64-2.7/ceygen/tests
copying ceygen/tests/**main**.py -> build/lib.macosx-10.8-x86_64-2.7/ceygen/tests
copying ceygen/tests/support.py -> build/lib.macosx-10.8-x86_64-2.7/ceygen/tests
copying ceygen/core.pxd -> build/lib.macosx-10.8-x86_64-2.7/ceygen
copying ceygen/dtype.pxd -> build/lib.macosx-10.8-x86_64-2.7/ceygen
copying ceygen/elemwise.pxd -> build/lib.macosx-10.8-x86_64-2.7/ceygen
copying ceygen/llt.pxd -> build/lib.macosx-10.8-x86_64-2.7/ceygen
copying ceygen/lu.pxd -> build/lib.macosx-10.8-x86_64-2.7/ceygen
copying ceygen/reductions.pxd -> build/lib.macosx-10.8-x86_64-2.7/ceygen
running build_ext
Compiling ceygen/core.pyx because it changed.
Compiling ceygen/dtype.pyx because it changed.
Compiling ceygen/elemwise.pyx because it changed.
Compiling ceygen/llt.pyx because it changed.
Compiling ceygen/lu.pyx because it changed.
Compiling ceygen/reductions.pyx because it changed.
Compiling ceygen/tests/bench.pyx because it changed.
Compiling ceygen/tests/test_core.pyx because it changed.
Compiling ceygen/tests/test_dispatch.pyx because it changed.
Compiling ceygen/tests/test_dtype.pyx because it changed.
Compiling ceygen/tests/test_elemwise.pyx because it changed.
Compiling ceygen/tests/test_llt.pyx because it changed.
Compiling ceygen/tests/test_lu.pyx because it changed.
Compiling ceygen/tests/test_reductions.pyx because it changed.
Cythonizing ceygen/core.pyx
Cythonizing ceygen/dtype.pyx
warning: ceygen/dtype.pyx:16:4: Unreachable code
warning: ceygen/dtype.pyx:18:4: Unreachable code
warning: ceygen/dtype.pyx:20:4: Unreachable code
warning: ceygen/dtype.pyx:22:4: Unreachable code
warning: ceygen/dtype.pyx:24:4: Unreachable code
Cythonizing ceygen/elemwise.pyx
Cythonizing ceygen/llt.pyx
Cythonizing ceygen/lu.pyx
Cythonizing ceygen/reductions.pyx
Cythonizing ceygen/tests/bench.pyx
Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/almacmillan/Sites/raptor2/raptor2/Ceygen/support/dist_cmd_test.py", line 31, in run
    self.run_command('build')  # build if not alredy run
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/almacmillan/Sites/raptor2/raptor2/Ceygen/support/dist_cmd_build_ext.py", line 45, in run
    annotate=self.annotate, force=self.force, build_dir=self.build_temp)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 785, in cythonize
    cythonize_one(_args[1:])
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 885, in cythonize_one
    result = compile([pyx_file], options)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 608, in compile
    return compile_multiple(source, options)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 586, in compile_multiple
    result = run_pipeline(source, options, context=context)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 433, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 328, in run_pipeline
    data = phase(data)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/ModuleNode.py", line 109, in process_implementation
    self.generate_c_code(env, options, result)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/ModuleNode.py", line 326, in generate_c_code
    self.body.generate_function_definitions(env, code)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 394, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 394, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 4146, in generate_function_definitions
    self.body.generate_function_definitions(self.scope, code)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 394, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 2861, in generate_function_definitions
    FuncDefNode.generate_function_definitions(self, env, code)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 1798, in generate_function_definitions
    self.generate_function_body(env, code)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 1567, in generate_function_body
    self.body.generate_execution_code(code)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 400, in generate_execution_code
    stat.generate_execution_code(code)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 5697, in generate_execution_code
    self.body.generate_execution_code(code)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 400, in generate_execution_code
    stat.generate_execution_code(code)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 6033, in generate_execution_code
    self.body.generate_execution_code(code)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 6475, in generate_execution_code
    fresh_finally_clause().generate_execution_code(code)
  File "/Users/almacmillan/.virtualenvs/coachfairer/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 6463, in fresh_finally_clause
    node_copy = copy.deepcopy(node)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(_args)
  File "/Users/almacmillan/.virtualenvs/coachfairer/bin/../lib/python2.7/copy_reg.py", line 93, in **newobj**
    return cls.**new**(cls, *args)
TypeError: object.**new**(cStringIO.StringO) is not safe, use cStringIO.StringO.**new**()

**Comment by Dapid** [comment]
I get the same on Linux. It is because the timing module in the benchmark is not thread safe, and cannot be used inside `prange`. I am working on a fix.

**Comment by strohel** [comment]
> I get the same on Linux. It is because the timing module in the benchmark is not thread safe, and cannot be used inside prange. I am working on a fix.

Oh nice, pull requests welcome. :)
