### ISSUE TITLE
`pip` install fails

### ISSUE THREAD

**Issue by Krastanov** [strohel/Ceygen#3]
```
  % pip install Ceygen                                                  
Downloading/unpacking Ceygen
  Downloading Ceygen-0.3.tar.gz
  Running setup.py (path:/tmp/pip-build-1uva238w/Ceygen/setup.py) egg_info for package Ceygen
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-1uva238w/Ceygen/setup.py", line 18, in <module>
        module.language = "c++"
    AttributeError: 'list' object has no attribute 'language'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-1uva238w/Ceygen/setup.py", line 18, in <module>

    module.language = "c++"

AttributeError: 'list' object has no attribute 'language'
```

**Comment by Krastanov** [comment]
on python3.4 in virtualenv

**Comment by Dapid** [comment]
I get the same on Python 2.7, virtualenv too.

**Comment by chrisidefix** [comment]
Anyone found a solution? I am getting the same error.

**Comment by strohel** [comment]
Hi all, sorry for replying so late - too little time lately, but I've been keeping an eye on this.

Has anyone tried with the current git version? It has seen quite some changes since 0.3 including builsystem changes. I may also do 0.4. -> some testing of current git would therefore greatly help.

**Comment by Dapid** [comment]
Just tested, still failing. I can try to upgrade it to setuptools and clean it up.

**Comment by chrisidefix** [comment]
The issue is related to this line: https://github.com/strohel/Ceygen/blob/master/setup.py#L18
Which hasn't changed since the 0.3 release from what I can see.

**Comment by strohel** [comment]
Just to share info: this should be solved once @Dapid's pull request is merged.

**Comment by kphretiq** [comment]
I just forked @Dapid's branch, merged and installed the fork via pip under python3 on ubuntu 16.04. All appears to be well. I'd rather not be using my silly fork. Is there a chance the pull request can be merged? Thanks!

**Comment by MFernandezCarmona** [comment]
Hi,
I don't know if it's related, but I get the following error:
manolofc@achilles:~$ pip install ceygen
Collecting ceygen
  Downloading Ceygen-0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gOjx4N/ceygen/setup.py", line 16, in <module>
        modules = create_extension_list(['ceygen/*.pyx', 'ceygen/tests/*.pyx'])
      File "/tmp/exp/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 767, in create_extension_list
        create_extension = ctx.options.create_extension or default_create_extension
    AttributeError: 'NoneType' object has no attribute 'options'

I'm using Ubuntu 16.04.
Thanks
